const wordsGerundSeason1 = [
    // Gerund
    { word: 'stop', category: '+ ing' },
    { word: 'postpone', category: '+ ing' },
    { word: 'admit', category: '+ ing' },
    { word: 'avoid', category: '+ ing' },
    { word: 'imagine', category: '+ ing' },
    { word: 'finish', category: '+ ing' },
    { word: 'consider', category: '+ ing' },
    { word: 'deny', category: '+ ing' },
    { word: 'enjoy', category: '+ ing' },
    { word: 'fancy', category: '+ ing' },
    { word: 'risk', category: '+ ing' },
    { word: 'give up', category: '+ ing' },
    { word: 'put off', category: '+ ing' },
    { word: 'go on / carry on', category: '+ ing' },
    { word: 'keep or keep on', category: '+ ing' },
    { word: 'mind', category: '+ ing' },
    { word: 'suggest', category: '+ ing' },

    // To infinitive
    { word: 'afford', category: '+ To' },
    { word: 'agree', category: '+ To' },
    { word: 'arrange', category: '+ To' },
    { word: 'decide', category: '+ To' },
    { word: 'deserve', category: '+ To' },
    { word: 'fail', category: '+ To' },
    { word: 'forget', category: '+ To' },
    { word: 'hope', category: '+ To' },
    { word: 'learn', category: '+ To' },
    { word: 'manage', category: '+ To' },
    { word: 'offer', category: '+ To' },
    { word: 'plan', category: '+ To' },
    { word: 'promise', category: '+ To' },
    { word: 'refuse', category: '+ To' },
    { word: 'threaten', category: '+ To' },

    // Verbs + Object + To + Verb
    { word: 'want', category: '+ To Object' },
    { word: 'ask', category: '+ To Object' },
    { word: 'help', category: '+ To Object' },
    { word: 'expect', category: '+ To Object' },
    { word: 'beg', category: '+ To Object' },
    { word: 'mean (intend)', category: '+ To Object' },
    { word: 'would like', category: '+ To Object' },
    { word: 'would prefer', category: '+ To Object' },
    { word: 'tell', category: '+ To Object' },
    { word: 'remind', category: '+ To Object' },
    { word: 'force', category: '+ To Object' },
    { word: 'encourage', category: '+ To Object' },
    { word: 'teach', category: '+ To Object' },
    { word: 'enable', category: '+ To Object' },
    { word: 'order', category: '+ To Object' },
    { word: 'warn', category: '+ To Object' },
    { word: 'invite', category: '+ To Object' },
    { word: 'persuade', category: '+ To Object' },
    { word: 'get (persuade)', category: '+ To Object' }
];
const wordsGerundSeason2 = [
    { question: 'I congratulated Liz _____ getting a new job.', answer: 'on' },
    { question: 'They accused us _____ telling lies.', answer: 'of' },
    { question: 'Nobody suspected the general _____ being a spy.', answer: 'of' },
    { question: 'What prevented you _____ coming to see us?', answer: 'from' },
    { question: 'The rain didn\'t stop us _____ enjoying our holiday.', answer: 'from' },
    { question: 'I forgot to thank them _____ helping me.', answer: 'for' },
    { question: 'Excuse me _____ being so late.', answer: 'for' },
    { question: 'Please forgive me _____ not writing to you.', answer: 'for' },

    { question: 'Are you interested _____ working for us?', answer: 'in' },
    { question: 'I\'m not very good _____ learning languages.', answer: 'at' },
    { question: 'Sue must be fed up _____ studying.', answer: 'with' },
    { question: 'What are the advantages _____ having a car?', answer: 'of' },
    { question: 'Thanks very much _____ inviting me to your party.', answer: 'for' },
    { question: 'How about _____ meeting for lunch tomorrow?', answer: 'about' },
    { question: 'Why don\'t you go out instead _____ sitting at home all the time?', answer: 'of' },
    { question: 'Carol went to work in spite _____ feeling ill.', answer: 'of' },

    { question: 'We talked _____ the problem.', answer: 'about' },
    { question: 'You must apologise _____ what you said.', answer: 'for' },

    { question: 'We talked _____ going to America.', answer: 'about' },
    { question: 'You must apologise _____ not telling the truth.', answer: 'for' },

    { question: 'Have you succeeded _____ finding a job yet?', answer: 'in' },
    { question: 'They insisted _____ paying for the meal.', answer: 'on' },
    { question: 'I\'m thinking _____ buying a house.', answer: 'of' },
    { question: 'I wouldn\'t dream _____ asking them for money.', answer: 'of' },
    { question: 'He doesn\'t approve _____ swearing.', answer: 'of' },
    { question: 'We have decided _____ moving to London.', answer: 'against' },
    { question: 'Do you feel _____ going out tonight?', answer: 'like' },
    { question: 'I\'m looking forward _____ meeting her.', answer: 'to' },
];

module.exports = {wordsGerundSeason1, wordsGerundSeason2}